name: MyTestSite
favicon: null
layout_spectrum: 0.22414095024578273
typography_spectrum: 0.47584206610918045
title: Randomness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.44642290682531893
  lightness: 0.6653844441752881
  saturation: 0.5991898914799094
  rhythmicContrast: 0.6344019414391369
purpose: []
