name: MyTestSite
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08404
title: Randomness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c3734'
    - '#fcfefb'
    - '#908f8d'
    - '#d3621d'
    - '#d72620'
  brandStrength: 0.75
  lightness: 0.6653844441752881
  saturation: 0.5991898914799094
  rhythmicContrast: 0.6344019414391369
purpose: []
